fail_fast: false
default_language_version:
  python: python3
default_stages:
  - commit
  - push
minimum_pre_commit_version: 2.16.0
repos:
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.3.3
    hooks:
      - id: prettier
