---
title: "Basic CELLxGENE workflow"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Wetlab Module}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Introduction
  
This vignette demonstrates a basic LaminDB workflow using the public CELLxGENE instance.
[CZ CELLxGENE Discover](https://cellxgene.cziscience.com/) is a standardised collection of scRNA-seq datasets and LaminDB makes it easy to query and access data in this repository.
We will go through the steps of finding and downloading a dataset using **{laminr}**, performing some simple analysis using **{Seurat}** and saving the results in a LaminDB database.

# Before we start

Before we go begin, please take some time to check out the Getting Started vignette (`vignette("laminr", package = "laminr")`).
In particular, make sure you have run the commands in the "Initial Setup" section.

# Connect to a LaminDB instance

- Connect to CELLxGENE instance
- Show instance object

# Downloading a dataset

- Show Artifact registry
- Go to CELLxGENE Lamin website
- Find a dataset, get the ID
- Cache and load the object locally

# Convert to Seurat

- CELLxGENE stores AnnData, we want Seurat
- Do the conversion

# Analysis

- Follow the Seurat tutorial to calculate marker genes
- Save results as a text file

# Add results

- Add the results as an artifact
- Render and add report (?)
