---
title: "Core classes"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Core classes}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r connect, include = FALSE}
library(laminr)
library(purrr)

db <- connect("laminlabs/lamindata")

core <- db$get_module("core")
```

```{r generate_docs, echo = FALSE, results = "asis"}
registry_names <- core$get_registry_names()
type_map <- c(
  "BigAutoField" = "integer64",
  "AutoField" = "integer",
  "CharField" = "character",
  "BooleanField" = "logical",
  "DateTimeField" = "POSIXct",
  "TextField" = "character",
  "ForeignKey" = "integer64",
  "BigIntegerField" = "integer64",
  "SmallIntegerField" = "integer",
  "JSONField" = "list"
)


for (registry_name in registry_names) {
  registry <- core$get_registry(registry_name)
  fields <- registry$get_fields()

  if (registry$is_link_table) {
    next
  }

  cat(paste0("## ", registry$class_name, "\n\n"))

  classes <- class(registry) |> discard(~ .x == "R6")
  class_urls <- paste0("`?", classes, "`")

  cat(paste0("Bases: ", paste(class_urls, collapse = ", "), "\n\n"))

  cat(paste0("### Simple fields\n\n"))
  
  simple_fields <- fields |> keep( ~
    is.null(.x$related_field_name) &&
    !grepl("^_", .x$field_name)
  )

  for (field in simple_fields) {
    field_type <-
      if (field$type %in% names(type_map)) {
        type_map[[field$type]]
      } else {
        field$type
      }
    cat(paste0("* `", field$field_name, "` (`", field_type, "`)\n"))
  }

  cat("\n\n")

  cat(paste0("### Relational fields\n\n"))

  relational_fields <- fields |> keep(~
    !is.null(.x$related_field_name) &&
    !grepl("^_", .x$field_name) &&
    !.x$is_link_table &&
    .x$related_module_name == "core"
  )

  for (field in relational_fields) {
    related_module <- db$get_module(field$related_module_name)
    related_registry <- related_module$get_registry(field$related_registry_name)
    cat(paste0("* `", field$field_name, "` ([", related_registry$class_name, "](#", related_registry$name, "))\n"))
  }

  cat("\n\n")
}
```