on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown.yaml

permissions: read-all

jobs:
  pkgdown:
    runs-on: ubuntu-latest

    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      LAMIN_API_KEY: ${{ secrets.LAMIN_API_KEY_TESTUSER1 }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website
          quarto-version: pre-release

      - name: Install {tiledbsoma}
        run: |
          options(repos = c("https://chanzuckerberg.r-universe.dev", getOption("repos")))
          install.packages("tiledbsoma")
        shell: Rscript {0}

      - name: Install lamindb
        run: |
          pip install 'lamindb[aws,bionty,wetlab]>=0.77.2'

      - name: Log in to Lamin
        run: |
          lamin login

      - name: Set lamindata as default instance
        run: |
          lamin connect laminlabs/lamindata

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Create built site artifact
        uses: actions/upload-artifact@v4
        with:
          name: pkgdown-site
          path: docs

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean: false
          branch: gh-pages
          folder: docs
